acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }
    
acme_hello_newpage:
    pattern:  /tutorial/{myVariable}
    defaults: { _controller: AcmeHelloBundle:Chris:rupert }