<?php

namespace Dsh\streetpicsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotosRepository extends EntityRepository
{
}
