dshstreetpics_homepage:
    pattern:  /photos/{name}
    defaults: { _controller: DshstreetpicsBundle:Default:index }

_photo:
    pattern: /photo/{photofile}
    defaults: { _controller: DshstreetpicsBundle:Photofile:photoshow }
