dshstreetpics_homepage:
    pattern:  /photos/{name}
    defaults: { _controller: DshstreetpicsBundle:Default:index }

_photo:
    pattern: /Photo
    defaults: { _controller: DshstreetpicsBundle:Photofile:Photo }
